server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    # API 프록시
    location /api/ {
        proxy_pass http://k8s-default-ingress-164f943143-393493025.ap-northeast-2.elb.amazonaws.com/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    
    # 정적 파일 캐시
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 30d;
        add_header Cache-Control "public";
        access_log off;
    }
    
    # 기본 정적 파일 서빙 (SPA 라우팅 걱정 없음)
    location / {
        try_files $uri $uri/ =404;
    }
}